blank_issues_enabled: false
contact_links:
  - name: Redivis Community Support
    url: https://github.com/redivis/meta/discussions/
    about: Please make features requests or ask and answer questions here.
  - name: Redivis Bugs
    url: https://github.com/redivis/meta/issues/
    about: Please report bugs here.
