blank_issues_enabled: false
contact_links:
  - name: Redivis Community Support
    url: https://github.com/redivis/meta/discussions/
    about: Make features requests or ask and answer questions here.
